---
 - name: Install Ruby and Bundler
   hosts: all
   become: true
   tasks:
   - name: Install packeg
     apt: name={{ item }} state=present
     with_items:
       - ruby-full
       - ruby-bundle
       - build-essential
